### ISSUE TITLE
Nebraska scenery towns have disappeared

### ISSUE THREAD

**Issue by nautofon** [truckermudgeon/truckermudgeon.github.io#1]
Scenery towns in Nebraska disappeared from the map. It looks like something went wrong with deploying last week’s update: [SceneryTownSource.tsx in the `maps` repository](https://github.com/truckermudgeon/maps/blob/f13e04b9c1e31ee1dbd46ecd6018880d1f04f1c4/packages/libs/ui/SceneryTownSource.tsx#L8) hasn’t been changed, but in the release on truckermudgeon.github.io, `sceneryTownsUrl` still went back to `kansas`.

**Comment by truckermudgeon** [comment]
Yikes, thanks for letting me know!

I remember running into some merge conflicts when updating the `truckermudgeon.github.io` repo last week... it looks like I resolved the conflicts incorrectly 🫠 

Fixed in https://github.com/truckermudgeon/truckermudgeon.github.io/commit/e01eacd1b2a9f56c13d0a005b91ae5b54cd8f829. Double-checking the deploy, I see that [Thedford](https://github.com/nautofon/ats-towns/blob/f3da1745ca2e215199c683e01674161b4713d480/NE/towns.geojson?short_path=0d1b1bb#L16) shows up properly:

<img width="524" alt="image" src="https://github.com/truckermudgeon/truckermudgeon.github.io/assets/121829201/7f1e1e69-9dc5-4cae-a6eb-0f2989f5b8af">

**Comment by nautofon** [comment]
Looks good to me. Thanks for the quick fix!
